sudo: required
dist: focal

env:
  - ROS_DISTRO=foxy
  # - git clone -v --progress https://github.com/doronhi/realsense.git  # This is Done automatically by TravisCI
before_install:
  # - echo 'deb http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo focal main' || sudo tee /etc/apt/sources.list.d/realsense-public.list
  - sudo apt-key adv --keyserver keys.gnupg.net --recv-key C8B3A55A6F3EFCDE || sudo apt-key adv --keyserver hkp://keys.gnupg.net:80 --recv-key C8B3A55A6F3EFCDE
  - sudo add-apt-repository "deb http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo $(lsb_release -cs) main"
  - sudo apt-get update -qq
  - sudo apt-get install librealsense2-dkms --allow-unauthenticated -y
  - sudo apt-get install librealsense2-dev --allow-unauthenticated -y

install:
  # install ROS:
  - sudo apt update && sudo apt install curl gnupg2 lsb-release -y
  - curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=$(dpkg --print-architecture)] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
  - sudo apt update -qq
  - sudo apt install ros-$ROS_DISTRO-ros-base -y
  - sudo apt install python3-colcon-common-extensions -y
  - sudo apt-get install python3-rosdep -y

  #Environment setup
  - echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> ~/.bashrc
  - source ~/.bashrc

  # install realsense2-camera
  - mkdir -p ~/ros2_ws/src/realsense-ros
  - mv * ~/ros2_ws/src/realsense-ros/     # This leaves behind .git, .gitignore and .travis.yml but no matter.
  - cd ~/ros2_ws
  - sudo rosdep init
  - rosdep update
  - rosdep install -i --from-path src --rosdistro $ROS_DISTRO -y
  - colcon build

  - . install/local_setup.bash

script:
    # download data:
  - bag_filename="http://realsense-hw-public.s3.amazonaws.com/rs-tests/TestData/outdoors_1color.bag";
  - wget $bag_filename -P "records/"
  - bag_filename="http://realsense-hw-public.s3-eu-west-1.amazonaws.com/rs-tests/D435i_Depth_and_IMU_Stands_still.bag";
  - wget $bag_filename -P "records/"

    # install packages for tests:
  - sudo apt-get install python3-pip
  - pip3 install numpy-quaternion tqdm
  # Run test:
  - python3 src/realsense-ros/realsense2_camera/scripts/rs2_test.py --all

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
