%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/galactic/.*$
%global __requires_exclude_from ^/opt/ros/galactic/.*$

Name:           ros-galactic-realsense2-camera
Version:        4.0.3
Release:        3%{?dist}%{?release_suffix}
Summary:        ROS realsense2_camera package

License:        Apache License 2.0
URL:            http://www.ros.org/wiki/RealSense
Source0:        %{name}-%{version}.tar.gz

Requires:       eigen3-devel
Requires:       ros-galactic-builtin-interfaces
Requires:       ros-galactic-cv-bridge
Requires:       ros-galactic-diagnostic-updater
Requires:       ros-galactic-geometry-msgs
Requires:       ros-galactic-image-transport
Requires:       ros-galactic-launch-ros
Requires:       ros-galactic-librealsense2
Requires:       ros-galactic-rclcpp
Requires:       ros-galactic-rclcpp-components
Requires:       ros-galactic-realsense2-camera-msgs
Requires:       ros-galactic-sensor-msgs
Requires:       ros-galactic-std-msgs
Requires:       ros-galactic-tf2
Requires:       ros-galactic-tf2-ros
Requires:       ros-galactic-ros-workspace
BuildRequires:  eigen3-devel
BuildRequires:  opencv-devel
BuildRequires:  ros-galactic-ament-cmake
BuildRequires:  ros-galactic-ament-cmake-gtest
BuildRequires:  ros-galactic-ament-lint-auto
BuildRequires:  ros-galactic-ament-lint-common
BuildRequires:  ros-galactic-builtin-interfaces
BuildRequires:  ros-galactic-cv-bridge
BuildRequires:  ros-galactic-diagnostic-updater
BuildRequires:  ros-galactic-geometry-msgs
BuildRequires:  ros-galactic-image-transport
BuildRequires:  ros-galactic-librealsense2
BuildRequires:  ros-galactic-rclcpp
BuildRequires:  ros-galactic-rclcpp-components
BuildRequires:  ros-galactic-realsense2-camera-msgs
BuildRequires:  ros-galactic-ros-environment
BuildRequires:  ros-galactic-sensor-msgs
BuildRequires:  ros-galactic-std-msgs
BuildRequires:  ros-galactic-tf2
BuildRequires:  ros-galactic-tf2-ros
BuildRequires:  ros-galactic-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
RealSense camera package allowing access to Intel T265 Tracking module and SR300
and D400 3D cameras

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/galactic/setup.sh" ]; then . "/opt/ros/galactic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/galactic" \
    -DAMENT_PREFIX_PATH="/opt/ros/galactic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/galactic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/galactic/setup.sh" ]; then . "/opt/ros/galactic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/galactic/setup.sh" ]; then . "/opt/ros/galactic/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/galactic

%changelog
* Wed Mar 16 2022 LibRealSense ROS Team <librs.ros@intel.com> - 4.0.3-3
- Autogenerated by Bloom

* Wed Mar 16 2022 LibRealSense ROS Team <librs.ros@intel.com> - 4.0.3-2
- Autogenerated by Bloom

* Wed Mar 16 2022 LibRealSense ROS Team <librs.ros@intel.com> - 4.0.3-1
- Autogenerated by Bloom

* Thu Feb 24 2022 Doron Hirshberg <doron.hirshberg@intel.com> - 4.0.2-1
- Autogenerated by Bloom

* Mon Nov 15 2021 Doron Hirshberg <doron.hirshberg@intel.com> - 3.2.3-1
- Autogenerated by Bloom

* Sun Jul 25 2021 Doron Hirshberg <doron.hirshberg@intel.com> - 3.2.2-2
- Autogenerated by Bloom

