%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-realsense2-description
Version:        2.3.2
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS realsense2_description package

License:        Apache 2.0
URL:            http://www.ros.org/wiki/RealSense
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-noetic-xacro
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-rosunit
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
RealSense Camera description package for Intel 3D D400 cameras

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Mon Nov 15 2021 Doron Hirshberg <doron.hirshberg@intel.com> - 2.3.2-1
- Autogenerated by Bloom

* Thu Jul 01 2021 Doron Hirshberg <doron.hirshberg@intel.com> - 2.3.1-1
- Autogenerated by Bloom

* Thu May 06 2021 Doron Hirshberg <doron.hirshberg@intel.com> - 2.3.0-1
- Autogenerated by Bloom

* Thu Apr 22 2021 Doron Hirshberg <doron.hirshberg@intel.com> - 2.2.24-1
- Autogenerated by Bloom

* Thu Feb 18 2021 Sergey Dorodnicov <sergey.dorodnicov@intel.com> - 2.2.22-1
- Autogenerated by Bloom

* Thu Dec 31 2020 Sergey Dorodnicov <sergey.dorodnicov@intel.com> - 2.2.21-1
- Autogenerated by Bloom

