%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-realsense2-camera
Version:        2.3.2
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS realsense2_camera package

License:        Apache 2.0
URL:            http://www.ros.org/wiki/RealSense
Source0:        %{name}-%{version}.tar.gz

Requires:       eigen3-devel
Requires:       ros-noetic-cv-bridge
Requires:       ros-noetic-ddynamic-reconfigure
Requires:       ros-noetic-diagnostic-updater
Requires:       ros-noetic-genmsg
Requires:       ros-noetic-image-transport
Requires:       ros-noetic-librealsense2
Requires:       ros-noetic-message-runtime
Requires:       ros-noetic-nav-msgs
Requires:       ros-noetic-nodelet
Requires:       ros-noetic-roscpp
Requires:       ros-noetic-sensor-msgs
Requires:       ros-noetic-std-msgs
Requires:       ros-noetic-std-srvs
Requires:       ros-noetic-tf
BuildRequires:  eigen3-devel
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-cv-bridge
BuildRequires:  ros-noetic-ddynamic-reconfigure
BuildRequires:  ros-noetic-diagnostic-updater
BuildRequires:  ros-noetic-genmsg
BuildRequires:  ros-noetic-image-transport
BuildRequires:  ros-noetic-librealsense2
BuildRequires:  ros-noetic-message-generation
BuildRequires:  ros-noetic-message-runtime
BuildRequires:  ros-noetic-nav-msgs
BuildRequires:  ros-noetic-nodelet
BuildRequires:  ros-noetic-roscpp
BuildRequires:  ros-noetic-sensor-msgs
BuildRequires:  ros-noetic-std-msgs
BuildRequires:  ros-noetic-std-srvs
BuildRequires:  ros-noetic-tf
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
RealSense Camera package allowing access to Intel T265 Tracking module and SR300
and D400 3D cameras

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Mon Nov 15 2021 Doron Hirshberg <doron.hirshberg@intel.com> - 2.3.2-1
- Autogenerated by Bloom

* Thu Jul 01 2021 Doron Hirshberg <doron.hirshberg@intel.com> - 2.3.1-1
- Autogenerated by Bloom

* Thu May 06 2021 Doron Hirshberg <doron.hirshberg@intel.com> - 2.3.0-1
- Autogenerated by Bloom

* Thu Apr 22 2021 Doron Hirshberg <doron.hirshberg@intel.com> - 2.2.24-1
- Autogenerated by Bloom

* Thu Feb 18 2021 Sergey Dorodnicov <sergey.dorodnicov@intel.com> - 2.2.22-1
- Autogenerated by Bloom

* Thu Dec 31 2020 Sergey Dorodnicov <sergey.dorodnicov@intel.com> - 2.2.21-1
- Autogenerated by Bloom

